### ISSUE TITLE
Maria hair not white

### ISSUE THREAD

**Issue by darkvanitas** [Lyall/MetaphorFix#77] opened 2024-10-16 20:17 UTC
Hello. I installed the newest version and has having problems with Maria's Hair. please see screenshot below both. looks cool tho

0.8.2
![image](https://github.com/user-attachments/assets/5f1f651d-4be8-4e75-bd08-9747e431e60b)

0.8.1
![image](https://github.com/user-attachments/assets/7e1e88b9-b614-436c-962e-529c11394295)

**Comment by vampirekatharsis** [comment] 2024-10-17 06:31
Yes I have the same problem. Just double confirming.

**Comment by Lyall** [comment] 2024-10-17 08:27
This is related to #75. I will revert the outlines behaviour to the way it was before, and the setting will be marked as experimental since it will still cause some visual issues.

**Comment by Lyall** [comment] 2024-10-17 10:47
I'm going to close this as a dupe of the other issue that I mentioned before. I have a test build I'll be posting over there that you can try though.

**Closed by Lyall** 2024-10-17 10:47 UTC
