### ISSUE TITLE
Any possibility of disabling the screen wobble during dialogue?

### ISSUE THREAD

**Issue by MakoEyes** [Lyall/MetaphorFix#26] opened 2024-10-10 21:50 UTC
I know you can disable screen shake in some areas in the menus, but there is still a subtle, but nauseating wobble to all dialogue boxes during cutscenes. I love the game, but the dialogue boxes are so distracting by constantly moving back and forth.

**Comment by Lyall** [comment] 2024-10-14 11:59
Dupe of #15.

**Closed by Lyall** 2024-10-14 11:59 UTC
